DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users (UserId TEXT PRIMARY KEY, MessageAmount INTEGER);
DROP TABLE IF EXISTS LastReads;
CREATE TABLE IF NOT EXISTS LastReads (ChannelId TEXT PRIMARY KEY, LastMessageId TEXT, Locked BOOLEAN);
