name = "focusonthebot"
main = "./src/server.ts"
compatibility_date="2023-05-18"
# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-focusonthebot"
database_id = "13a4cfda-36f5-45d6-ac50-b0eff48454e4"
