name = "focusonthebot"
main = "./src/server.ts"
compatibility_date="2023-05-18"
# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-focusonthebot"
database_id = "c7fc1e3e-2be5-4fbc-9d10-2a6116c7aa3f"