name = "focusonthebot"
main = "./src/server.ts"
compatibility_date="2023-05-18"

# default vars
vars = { ENVIRONMENT = "prod" }
d1_databases = [
  { binding = "DB", database_name = "prod-focusonthebot", database_id = "13a4cfda-36f5-45d6-ac50-b0eff48454e4" }
]

# staging vars override, not set yet, TODO, see 
[env.staging]
vars = { ENVIRONMENT = "staging" }
name = "focusonthe-staging"
d1_databases = [
  { binding = "DB", database_name = "<db_name>", database_id = "<db_id>" }
]

# development vars override (just use wrangler.local.toml, less of a headache q_q)
[env.dev]
vars = { ENVIRONMENT = "dev" }
name = "mypotatobot"
d1_databases = [
  { binding = "DB", database_name = "<db_name>", database_id = "<db_id>" }
]
